### ISSUE TITLE
How should I add a CorsFilter?

### ISSUE THREAD

**Issue by hxh-robb** [soulwing/cas-mock-server#7]
This might be a stupid question, I'd like to add CORS related header to all the response, I've tried following Filter class and then rebuild redeploy to the tomcat, but seems like the filter class didn't get scanned.

```
@Provider
public class CorsFilter implements ContainerResponseFilter {

    @Override
    public void filter(ContainerRequestContext requestContext, 
      ContainerResponseContext responseContext) throws IOException {
          responseContext.getHeaders().add(
            "Access-Control-Allow-Origin", "*");
          responseContext.getHeaders().add(
            "Access-Control-Allow-Credentials", "true");
          responseContext.getHeaders().add(
           "Access-Control-Allow-Headers",
           "origin, content-type, accept, authorization");
          responseContext.getHeaders().add(
            "Access-Control-Allow-Methods", 
            "GET, POST, PUT, DELETE, OPTIONS, HEAD");
    }
}
```

I was wondering what's the proper way to do the trick, thanks

**Comment by ceharris** [comment]
The short answer is... I would have expected that to work exactly the way you expected it to work; i.e. implement `ContainerResponseFilter` and annotate the class using `@Provider`. It's just plain old JAX-RS using Jersey as the provider so that _should_ work.

**Comment by ceharris** [comment]
Maybe add a `@PostConstruct` method that logs something just to confirm that it really isn't being loaded as a provider?

**Comment by ceharris** [comment]
Okay, so I wrote a demo filter of my own and confirmed that it does in fact load the filter, as shown in the log snippet below. After I did so I realized that while your filter probably is going to add the CORS headers, it's adding them to the "wrong" response. That filter will sit in front of the `/serviceValidate` and `/proxyValidate` paths, which are typically called by a backend that is validating a CAS ticket presented by a frontend app. Typically, you'd want the CORS filters in your backend that communicates with the frontend app. Hope this helps!

```
24-Mar-2021 13:07:47.832 INFO [localhost-startStop-1] org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer.addServletWithDefaultConfiguration Registering the Jersey servlet application, named javax.ws.rs.core.Application, with the following root resource and provider classes:
[class org.soulwing.cas.server.web.MyDemoFilter, class org.glassfish.jersey.server.wadl.internal.WadlResource, class org.soulwing.cas.server.web.ProtocolEndpoint]
2
```

**Comment by hxh-robb** [comment]
> Maybe add a `@PostConstruct` method that logs something just to confirm that it really isn't being loaded as a provider?

The log shows that CorsFilter is actually loaded, the reason it didn't get used is because it only works for `ProtocolEndpoint`,

For login, it's driven by `LoginBean` and the `login/index.xhtml`

> Okay, so I wrote a demo filter of my own and confirmed that it does in fact load the filter, as shown in the log snippet below. After I did so I realized that while your filter probably is going to add the CORS headers, it's adding them to the "wrong" response. That filter will sit in front of the `/serviceValidate` and `/proxyValidate` paths, which are typically called by a backend that is validating a CAS ticket presented by a frontend app. Typically, you'd want the CORS filters in your backend that communicates with the frontend app. Hope this helps!
> 
> ```
> 24-Mar-2021 13:07:47.832 INFO [localhost-startStop-1] org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer.addServletWithDefaultConfiguration Registering the Jersey servlet application, named javax.ws.rs.core.Application, with the following root resource and provider classes:
> [class org.soulwing.cas.server.web.MyDemoFilter, class org.glassfish.jersey.server.wadl.internal.WadlResource, class org.soulwing.cas.server.web.ProtocolEndpoint]
> 2
> ```
Yes, my findings are the same as yours; 
But in my scenario, the login page is where CORS error happened, so I need to add the CORS headers inside `LoginServlet$doGet` before the `LOGIN_FORM_PATH` forward

**Comment by hxh-robb** [comment]
Thanks @ceharris for your kindly replies,

I'll close this issue since I've found a solution. Later I'll create a PR that implements the `CorsFilter` feature.

**Comment by ceharris** [comment]
Another approach (as opposed to modifying `LoginServlet`) would be to implement a `ServletFilter`.

```
@WebFilter("/login/*")
public class CorsFilter implements ServletFilter {
   // ...
}
```
There are a couple of additional boilerplate methods to implement in the interface and the `ServletRequest` and `ServletResponse` types need to be cast to `HttpServletRequest` and `HttpServletResponse`, but it's conceptually similar to a JAX-RS filter and you shouldn't have trouble finding examples.

If you want to do a PR for this, please consider allowing the allowed origins to be specified via an environment variable.

**Comment by hxh-robb** [comment]
> If you want to do a PR for this, please consider allowing the allowed origins to be specified via an environment variable.

sure
